# name: Tests

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   container-job:
#     runs-on: ubuntu-latest
#     container: node:14
#     services:
#       postgres:
#         image: postgres
#         env:
#           POSTGRES_PASSWORD: postgres
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js 14.x
#       uses: actions/setup-node@v2
#       with:
#         node-version: 14.x
#         cache: npm
#     - run: |
#         npm ci
#         DB_URL=postgresql://postgres:postgres@postgres:5432 npx jest --coverage --passWithNoTests
#         npx codecov
